login_check:
    path: /login_check

logout:
    path: /logout

library_app_default:
    pattern:  /
    defaults: { _controller: LibraryAppBundle:Default:index, _locale: en }
    methods:  [GET]

library_app:
    resource: "@LibraryAppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|fr
