security:
    providers:
        main:
            entity: { class: LibraryAppBundle:User }

    encoders:
        Library\Bundle\AppBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/(en)/login
            security: false

        default:
            pattern: ^/
            anonymous: false
            form_login:
                login_path: _login
                check_path: login_check
            logout:
                path: /logout
                target: /
