security:
    providers:
        in_memory:
            memory:
                users:
                    administrator:  { password: default, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/(en)/login
            security: false

        default:
            pattern: ^/
            anonymous: false
            form_login:
                login_path: _login
                check_path: login_check
            logout:
                path: /logout
                target: /